# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  openj9:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '8' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
        openjdk_impl: 'openj9'
    - run: ./gradlew assembleRelease
  hotspot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '8' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
        openjdk_impl: 'hotspot'
    - run: ./gradlew assembleRelease
